<a href="https://colab.research.google.com/github/Prime182/stats_with_numpy/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating arrays

In [3]:
# 0 D array
import numpy as np
a =np.array(42)
print(a)

42


In [9]:
# 1 D array

# using list
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

# using tuple
import numpy as np
a = np.array((1,2,3,4,5))
print(a)

[1 2 3 4 5]
[1 2 3 4 5]


In [19]:
# 2 D array
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print("2 Dim array")
print(b)

# 3 D array
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print("\n3 Dim array")
print("\n",c)


2 Dim array
[[1 2 3]
 [4 5 6]]

3 Dim array

 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [22]:
print("No. of Dimensions =",a.ndim)
print("No. of Dimensions =",b.ndim)
print("No. of Dimensions =",c.ndim)

No. of Dimensions = 1
No. of Dimensions = 2
No. of Dimensions = 3


In [28]:
# Creation of arrays with different dimensions
d = np.array(1,ndmin=5)
print(d)
d = np.array([[1,2,3],[1,2,3]],ndmin=5)
print(d)


[[[[[1]]]]]
[[[[[1 2 3]
    [1 2 3]]]]]


# Array indexing

In [35]:
# 1 d
a = np.array([1,2,3,4,5])
print(a[1])

2


In [52]:
# 2 d
b = np.array([[1,2,3],[4,5,6]])
print(b[0],b[1]) # accessing all elements in each dimension
print(b[0,1], b[1,0]) # accessing elements individually in each dimension

# 3 d
c = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(c[0,1,2]) # 0 => [1,2,3],[4,5,6]. 1 => [4,5,6]. 2 => 6

[1 2 3] [4 5 6]
2 4
6


# Slicing